# Generated by Django 4.1.2 on 2024-07-24 15:27

import app.models.user
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_release_0_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.CreateModel(
            name='SpotRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('spot', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='spot_rating', to='app.spot')),
                ('user', models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='spot_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shop_rating', to='app.shop')),
                ('user', models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='shop_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('bar', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bar_rating', to='app.bar')),
                ('user', models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='bar_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='spotrating',
            constraint=models.UniqueConstraint(fields=('spot', 'user'), name='unique_spot_rate_for_user'),
        ),
        migrations.AddConstraint(
            model_name='shoprating',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='unique_shop_rate_for_user'),
        ),
        migrations.AddConstraint(
            model_name='barrating',
            constraint=models.UniqueConstraint(fields=('bar', 'user'), name='unique_bar_rate_for_user'),
        ),
    ]
