# Generated by Django 4.1.2 on 2024-07-24 17:03

import app.models.user
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bar_price_alter_shop_price_spotrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='price',
        ),
        migrations.AlterField(
            model_name='barrating',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='bar_rating_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoprating',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='shop_rating_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotrating',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='spot_rating_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShopPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shop_price', to='app.shop')),
                ('user', models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='shop_price_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('bar', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bar_price', to='app.bar')),
                ('user', models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='bar_price_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shopprice',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='unique_shop_price_for_user'),
        ),
        migrations.AddConstraint(
            model_name='barprice',
            constraint=models.UniqueConstraint(fields=('bar', 'user'), name='unique_bar_price_for_user'),
        ),
    ]
