# Generated by Django 4.1 on 2022-08-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='longitude',
            new_name='lng',
        ),
    ]
