# Generated by Django 4.1.2 on 2023-04-01 10:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('forest', 'Forest'), ('river', 'River'), ('lake', 'Lake'), ('cliff', 'Cliff'), ('mountain', 'Mountain'), ('beach', 'Beach'), ('sea', 'Sea'), ('city', 'City'), ('pov', 'Pov')], max_length=100),
        ),
    ]
