# Generated by Django 4.1.2 on 2024-11-18 20:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_bar_price_remove_shop_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('regular', 'Regular'), ('snack', 'Snack'), ('cellar', 'Cellar'), ('rooftop', 'Rooftop'), ('restaurant', 'Restaurant')], max_length=100),
        ),
    ]
