# Generated by Django 4.1.2 on 2024-11-18 20:46

import app.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bar_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user), related_name='bars', to=settings.AUTH_USER_MODEL),
        ),
    ]
