# Generated by Django 4.1.2 on 2022-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_shop_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture/'),
        ),
    ]
