# Generated by Django 4.1.2 on 2022-12-12 22:40

import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models

import app.models.user


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user),
                                    related_name='bar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user),
                                    related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spot',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=models.SET(app.models.user.get_default_user),
                                    related_name='spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bar',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('tobacco', 'Tobacco'), ('food', 'Food'),
                                                                       ('card', 'Card'), ('choice', 'Choice'),
                                                                       ('outdoor', 'Outdoor')], max_length=100,
                                                              null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bio', 'Bio'), ('craft', 'Craft'),
                                                                                   ('fresh', 'Fresh'), ('card', 'Card'),
                                                                                   ('choice', 'Choice')],
                                                              max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('bench', 'Bench'), ('covered', 'Covered'),
                                                                       ('toilet', 'Toilet'), ('store', 'Store'),
                                                                       ('trash', 'Trash'), ('parking', 'Parking')],
                                                              max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('regular', 'Regular'), ('snack', 'Snack'),
                                                                       ('cellar', 'Cellar'), ('rooftop', 'Rooftop')],
                                                              max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('store', 'Store'), ('super', 'Super'),
                                                                       ('hyper', 'Hyper'), ('cellar', 'Cellar')],
                                                              max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True,
                                                              choices=[('forest', 'Forest'), ('river', 'River'),
                                                                       ('mountain', 'Mountain'), ('beach', 'Beach'),
                                                                       ('city', 'City'), ('pov', 'Pov')],
                                                              max_length=100, null=True),
        ),
    ]
