# Generated by Django 4.1.2 on 2024-11-19 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.models.user.user
import app.utils.date


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_alter_bar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailChange',
            fields=[
                ('new_email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField(default=app.utils.date.now_plus_one_week, editable=False)),
                ('user', models.ForeignKey(default=app.models.user.user.get_default_user, editable=False,
                                           on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss',
                                           related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_user_email_change',
            },
        ),
    ]
