# Generated by Django 4.1.2 on 2022-12-23 16:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bar_price_shop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('tobacco', 'Tobacco'), ('food', 'Food'), ('card', 'Card'), ('choice', 'Choice'), ('outdoor', 'Outdoor')], default='[]', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bar',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('regular', 'Regular'), ('snack', 'Snack'), ('cellar', 'Cellar'), ('rooftop', 'Rooftop')], default='[]', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bio', 'Bio'), ('craft', 'Craft'), ('fresh', 'Fresh'), ('card', 'Card'), ('choice', 'Choice')], default='[]', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('store', 'Store'), ('super', 'Super'), ('hyper', 'Hyper'), ('cellar', 'Cellar')], default='[]', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spot',
            name='modifiers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bench', 'Bench'), ('covered', 'Covered'), ('toilet', 'Toilet'), ('store', 'Store'), ('trash', 'Trash'), ('parking', 'Parking')], default='[]', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spot',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('forest', 'Forest'), ('river', 'River'), ('mountain', 'Mountain'), ('beach', 'Beach'), ('city', 'City'), ('pov', 'Pov')], default='[]', max_length=100),
            preserve_default=False,
        ),
    ]
