version: "3.9"

services:
  nginx:
    container_name: ${NGINX_NAME}
    build:
      context: .
      dockerfile: ./.conf/development/nginx/Dockerfile
    ports:
      - ${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}
    environment:
      SERVER_HTTP_PORT: ${SERVER_HTTP_PORT}
      BACKEND_NAME: ${BACKEND_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      - beer_crackerz_static:/vol/static
  backend:
    container_name: ${BACKEND_NAME}
    build:
      context: .
      dockerfile: ./.conf/development/back/Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      DEBUG: ${BACKEND_DEBUG}
      ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./back:/back
      - beer_crackerz_static:/static
    depends_on:
      - db
  db:
    image: postgres:${DB_POSTGRES_VERSION}
    container_name: ${DB_HOST}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - beer_crakerz_db:/var/lib/postgresql/data
volumes:
  beer_crakerz_db:
    name: beer_crakerz_db
  beer_crackerz_static:
    name: beer_crackerz_static
