name: ${PROJECT_NAME}
services:
  nginx:
    container_name: ${NGINX_NAME}
    restart: always
    build:
      context: .
      dockerfile: ./.conf/production/nginx/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      BACKEND_PROXY: ${BACKEND_NAME}:${BACKEND_PORT}
    volumes:
      - bc_static_files:/vol/static
      - bc_media:/vol/media
      - bc_logs:/var/log/nginx/back
    depends_on:
      - backend
  backend:
    container_name: ${BACKEND_NAME}
    restart: always
    build:
      context: .
      dockerfile: ./.conf/production/back/Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      SERVER_URL: ${SERVER_URL}
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      DEBUG: ${BACKEND_DEBUG}
      ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BACKEND_USE_EMAIL_FILE_SYSTEM: ${BACKEND_USE_EMAIL_FILE_SYSTEM}
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}
    volumes:
      - bc_static_files:/vol/static
      - bc_media:/vol/media
    depends_on:
      - db
  db:
    image: postgres:${DB_POSTGRES_VERSION}
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    volumes:
      - bc_db:/var/lib/postgresql/data
volumes:
  bc_db:
    name: ${VOLUME_DB}
  bc_static_files:
    name: ${VOLUME_STATIC_FILES}
  bc_media:
    name: ${VOLUME_MEDIA}
  bc_logs:
    name: ${VOLUME_LOGS}
