export default Object.freeze({
  blue: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-blue.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 42],
    iconAnchor: [12, 42],
    popupAnchor: [1, -34],
    shadowSize: [42, 42],
  }),
  red: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-red.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 42],
    iconAnchor: [12, 42],
    popupAnchor: [1, -34],
    shadowSize: [42, 42],
  }),
  green: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-green.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 42],
    iconAnchor: [12, 42],
    popupAnchor: [1, -34],
    shadowSize: [42, 42],
  }),
  black: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-black.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 42],
    iconAnchor: [12, 42],
    popupAnchor: [1, -34],
    shadowSize: [42, 42],
  }),
  user: new window.L.Icon({
    iconUrl: '/static/img/marker/user-position.png',
    shadowUrl: '/static/img/marker/user-position-shadow.png',
    iconSize: [32, 32],
    iconAnchor: [16, 16],
    popupAnchor: [1, -34],
    shadowSize: [32, 32],
  }),
});
