export default Object.freeze({
  blue: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-blue.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  gold: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-gold.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  red: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-red.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  green: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-green.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  orange: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-orange.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  yellow: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-yellow.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  violet: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-violet.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  grey: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-grey.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  black: new window.L.Icon({
    iconUrl: '/static/img/marker/marker-icon-black.png',
    shadowUrl: '/static/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  user: new window.L.Icon({
    iconUrl: '/static/img/marker/user-position.png',
    shadowUrl: '/static/img/marker/user-position-shadow.png',
    iconSize: [32, 32],
    iconAnchor: [16, 16],
    popupAnchor: [1, -34],
    shadowSize: [32, 32],
  }),
});
