export default Object.freeze({
  blue: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-blue.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  gold: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-gold.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  red: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-red.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  green: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-green.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  orange: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-orange.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  yellow: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-yellow.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  violet: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-violet.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  grey: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-grey.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  black: new window.L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-black.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  user: new window.L.Icon({
    iconUrl: 'assets/img/marker/user-position.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [32, 32],
    iconAnchor: [16, 41],
    popupAnchor: [1, -34],
    shadowSize: [32, 32],
  }),
});
