export default Object.freeze({
  blue: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-blue.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  gold: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-gold.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  red: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-red.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  green: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-green.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  orange: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-orange.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  yellow: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-yellow.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  violet: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-violet.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  grey: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-grey.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
  black: new L.Icon({
    iconUrl: 'assets/img/marker/marker-icon-2x-black.png',
    shadowUrl: 'assets/img/marker/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41],
  }),
});
